### ISSUE TITLE
Release version 1.3 and update opam package

### ISSUE THREAD

**Issue by sacerdot** [whitequark/ocaml-expat#5]
Dear Catherine,

can you turn 1.3 into an official release and update the opam package, please?

Thanks and happy new year!
C.S.C.

**Comment by sacerdot** [comment]
I realised (and checked) that 1.3 is working with ocaml >= 4.14.1 too. I can update the opam package myself, but only after you do an official release on github (to generate the tarballs used by opam).

**Comment by whitequark** [comment]
Is https://github.com/whitequark/ocaml-expat/releases/tag/v1.3.0 okay?

**Comment by sacerdot** [comment]
Yes, it is. I am preparing the opam release. It will take some time due to ocaml-expat requiring different libs on different architectures and native compilation also missing on some architectures.
